# CI job that builds, tests and analyzes the branch / pull requets

name: Maven Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Read Pull Request Coordinates
        if: github.event_name == 'pull_request'
        uses: actions/github-script@0.9.0
        with:
          # payload schema: https://developer.github.com/v3/activity/events/types/#pullrequestevent
          script: |
            //console.log("context.payload.pull_request: " + JSON.stringify(context.payload.pull_request));
            //console.log("context.payload.pull_request.diff_url: " + context.payload.pull_request.diff_url);
            //console.log("context.payload.pull_request[head]: " + context.payload.pull_request["head"]);
            //console.log("context.payload.pull_request.head.ref: " + context.payload.pull_request.head.ref);
            //console.log("context.payload.pull_request.head.ref: " + JSON.stringify(context.payload.pull_request.head.ref));
            core.exportVariable('PULL_REQUEST_BRANCH_NAME',context.payload.pull_request.head.ref);
            core.exportVariable('PULL_REQUEST_TARGET_BRANCH_NAME',context.payload.pull_request.base.ref);
            core.exportVariable('PULL_REQUEST_NUMBER',context.payload.number.toString());
#            console.log("context.payload.number: " + context.payload.number);
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Checkout
        uses: actions/checkout@v2
      - name: Read Branch Coordinates
        if: github.event_name == 'push'
        uses: actions/github-script@0.9.0
        with:
          # payload schema: https://developer.github.com/v3/activity/events/types/#pushevent
          script: |
            const fullGitRef = context.ref;
            const branchName = fullGitRef.replace(/refs\/\w+\//i,'');
            core.exportVariable('PUSH_BRANCH_NAME', branchName);
      - name: Read Pull Request Coordinates
        if: github.event_name == 'pull_request1'
        uses: actions/github-script@0.9.0
        with:
          # payload schema: https://developer.github.com/v3/activity/events/types/#pullrequestevent
          script: |
            console.log("context.payload.pull_request.head.ref: " + context.payload.pull_request.head.ref);
            console.log("context.payload.pull_request.head.ref: " + JSON.stringify(context.payload.pull_request.head.ref));
            core.exportVariable('TEST',context.payload.pull_request.head.ref);
      - name: Build with Maven
        run: mvn --file pom.xml --batch-mode package
      - name: Sonar Analysis with Maven (sonarcloud.io) - Branch
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: |
          mvn --file pom.xml --batch-mode sonar:sonar \
          -Dsonar.login=$SONARCLOUD_TOKEN \
          -Dsonar.branch.name=$PUSH_BRANCH_NAME
      - name: Sonar Analysis with Maven (sonarcloud.io) - Pull Request
        # github.head_ref The head_ref or source branch of the pull request in a workflow run.
        # github.base_ref The base_ref or target branch of the pull request in a workflow run.
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: |
          mvn --file pom.xml --batch-mode sonar:sonar \
          -Dsonar.login=$SONARCLOUD_TOKEN \
          -Dsonar.pullrequest.branch=$PULL_REQUEST_BRANCH_NAME \
          -Dsonar.pullrequest.base=$PULL_REQUEST_TARGET_BRANCH_NAME \
          -Dsonar.pullrequest.key=$PULL_REQUEST_NUMBER
      - name: Upload to CoPilot
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: bash <(curl -s https://copilot.blackducksoftware.com/ci/githubactions/scripts/upload)
