# CI job that builds, tests and analyzes the branch / pull request

name: Maven Build

on:
  pull_request:
    paths-ignore: 
      - '.github/**'
      - '!.github/workflows/maven.yml'
  push:
    paths-ignore: 
      - '.github/**'
      - '!.github/workflows/maven.yml'
    # disable temporary
    branches-ignore:
      - 'bugfix/GH-16_*'
#      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3.9.0
        with:
          distribution: temurin
          java-version: 11
      - name: Checkout
        uses: actions/checkout@v3.2.0
      - name: Fetch whole git history
        run: |
          git fetch --prune --unshallow
      - name: Read Git Coordinates - Branch
        id: push-branch-name
        if: github.event_name == 'push'
        uses: actions/github-script@v6.3.3
        with:
          # payload schema: https://developer.github.com/v3/activity/events/types/#pushevent
          script: |
            const fullGitRef = context.ref;
            const branchName = fullGitRef.replace(/refs\/\w+\//i,'');
            core.setOutput('PUSH_BRANCH_NAME', branchName);
      - name: Read Git Coordinates - Pull Request
        id: pull-request-name
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6.3.3
        with:
          # payload schema: https://developer.github.com/v3/activity/events/types/#pullrequestevent
          script: |
            core.setOutput('PULL_REQUEST_SOURCE_BRANCH_NAME', context.payload.pull_request.head.ref);
            core.setOutput('PULL_REQUEST_TARGET_BRANCH_NAME', context.payload.pull_request.base.ref);
            core.setOutput('PULL_REQUEST_NUMBER', context.payload.number.toString());
      - name: Cache local Maven repository - build
        uses: actions/cache@v3.2.0
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/**/*-SNAPSHOT
          key: ${{ runner.os }}-maven-build-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-build-
      - name: Build with Maven
        run: |
          mvn --file pom.xml --batch-mode \
            install -P ci-run
      - name: Cache Sonar Cache
        uses: actions/cache@v3.2.0
        with:
          path: |
            ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-sonar-
      - name: Run simple test project analysis
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./src/test/projects/simple
        run: |
          mvn --file pom.xml --batch-mode \
            sonar:sonar sonar-quality-gate:check \
            -Dsonar.login=${{ secrets.SONARCLOUD_TOKEN }}
      - name: Run multi-module test project analysis
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        working-directory: ./src/test/projects/multi-module
        run: |
          mvn --file pom.xml --batch-mode \
            sonar:sonar sonar-quality-gate:check
      - name: Sonar Analysis with Maven (sonarcloud.io) - Branch
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: |
          mvn --file pom.xml --batch-mode \
            sonar:sonar \
            -Dsonar.branch.name=${{ steps.push-branch-name.outputs.PUSH_BRANCH_NAME }}
      - name: Sonar Analysis with Maven (sonarcloud.io) - Pull Request
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: |
          mvn --file pom.xml --batch-mode \
            sonar:sonar \
            -Dsonar.pullrequest.branch=${{ steps.pull-request-name.outputs.PULL_REQUEST_SOURCE_BRANCH_NAME }} \
            -Dsonar.pullrequest.base=${{ steps.pull-request-name.outputs.PULL_REQUEST_TARGET_BRANCH_NAME }} \
            -Dsonar.pullrequest.key=${{ steps.pull-request-name.outputs.PULL_REQUEST_NUMBER }}
  site:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3.9.0
        with:
          distribution: temurin
          java-version: 11
      - name: Checkout
        uses: actions/checkout@v3.2.0
      - name: Cache local Maven repository - site
        uses: actions/cache@v3.2.0
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-site-${{ hashFiles('pom.xml','src/site/site.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-site-
      - name: Build with Maven
        run: |
          mvn --file pom.xml --batch-mode \
            site
      - name: store site as job artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: site
          path: target/site/
