# CI job that builds, tests and analyzes the branch / pull requets

name: Maven Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Read Coordinates
        uses: actions/github-script@0.9.0
        with:
          script: |
            console.log("context: " + JSON.stringify(context));
            console.log("github: " + JSON.stringify(github));
